language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen

script: make docs

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: dev

